#!/bin/bash

if [ $# -ge 1 ];then
    if [[ $1 == "om" ]]; then
        echo "push to master"
        git push origin master
    elif [[ $1 == "di" ]]; then
        git diff
    elif [[ $1 == "l" ]]; then
        git log --pretty=oneline --abbrev-commit
    elif [[ $1 == "add" ]]; then
        git add . 
    elif [[ $1 == "s" ]]; then
        git status 
    elif [[ $1 == "co" ]]; then
        git checkout $2 
    elif [[ $1 == "reset" ]]; then
        echo "cancel commit"
        git reset .
    else
        echo "comment: '$1'"
        git commit -a -m "'$1'"
    fi

fi
